### ISSUE TITLE
What is Slag?

### ISSUE THREAD

**Issue by technyk** [Seggan/Liquid#14]
Hi,
today I found one specific item, named "Slag". When I went ahead and wanted to see how to craft it, there was no crafting except for the solidifer and Molten Slag one.  Is there any explanation on how to get this item? I have searched through the internet, but there was no info on it. Sorry if I'm writing into the wrong section, but I didn't know where to ask. Thanks in advance.
![image](https://user-images.githubusercontent.com/54066232/145861358-40cbd839-9ee6-4f7f-8e22-b5f74fabd61f.png)

**Comment by Seggan** [comment]
Slag is a byproduct of centrifuging. It can be used in the grindstone/electric ore crusher to make sifted ore. For further discussion here's the Discord of the addon: https://discord.gg/SqD3gg5SAU
