### ISSUE TITLE
Mixer recipes

### ISSUE THREAD

**Issue by Playgono** [Seggan/Liquid#3]
## Description (Required)

Whilst attempting to create hardened metal whenever I would put the molten metals required (Copper, aluminum, steel, zinc) the steel and aluminum get ignored and the copper and zinc combine to make bronze instead. No matter the orientation or order of the molten metals put in the mixer the copper and zinc always combined to make the bronze.

## Steps to reproduce the Issue (Required)

Try to make Molten Hardened Metal by putting Molten Aluminum, Molten steel, Molten copper, Molten zinc in a mixer and will result in the copper and zinc to create bronze and not the intended recipe of Hardened Metal
## Expected behavior (Required)

Make Molten Hardened Metal

## Environment (Required)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: DEV-91 (git e42a05d1)
 - Slimefun Version: DEV-765 (git 96c4d908)
 - Plugin Version:  DEV-4 (git 68ecd4a8)

**Comment by Seggan** [comment]
Update to build #5
