### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by MagmaSlime123** [Seggan/Liquid#5]
## Description (Required)
Liquid is spamming errors about its category.

## Steps to reproduce the Issue (Required)
Use the plugin.

## Expected behavior (Required)
My console not being spammed.

## Server Log / Error Report
https://pastebin.com/hLt1UKki

## Environment (Required)

(These are about a day old, and I've updated everything since then.)
![2021-01-10_11 03 36](https://user-images.githubusercontent.com/51277766/104215183-48488980-53ed-11eb-98ad-e312c5ef70eb.png)
![2021-01-10_11 03 38](https://user-images.githubusercontent.com/51277766/104215192-4a124d00-53ed-11eb-9dc5-04e2686294d4.png)

**Comment by Seggan** [comment]
The developer of Slimefun has notified me that the error isn't about Liquid, it's a Slimefun error. This should be fixed soon.

**Comment by Seggan** [comment]
Fixed in pull #4 (build 6)

**Comment by TheBusyBiscuit** [comment]
> The developer of Slimefun has notified me that the error isn't about Liquid, it's a Slimefun error. This should be fixed soon.

No, I definitely did not say that. It is an error from Liquid.

**Comment by Seggan** [comment]
Well you did say that it was a Slimefun build that broke it...

**Comment by TheBusyBiscuit** [comment]
I did not.
Liquid was built against an older version of Slimefun, so it needed to be updated.
I even went ahead and pr'd a fix to your project for you... So please don't pretend the opposite.
