### ISSUE TITLE
Mixer Recipes Error

### ISSUE THREAD

**Issue by xMikux** [Seggan/Liquid#6]
## Description (Required)
When click in Mixer Recipes category
the Back enchat book can take down and send the error.
 
## Steps to reproduce the Issue (Required)
1. Open Guide
2. Click in Mixer Recipes
3. Click the Back enchant book and the enchant book take down, the console send error.
![2021-01-16_23 02 13](https://user-images.githubusercontent.com/26039249/104815374-0b4a2000-584f-11eb-9e69-104836b0ccbd.png)

## Expected behavior (Required)
The back enchant book won't be able to take down.

## Server Log / Error Report
https://pastebin.com/bZ7v8zjL

## Environment (Required)

 - Minecraft Version: Paper git-Paper-409 (MC: 1.16.4)
 - CS-CoreLib Version: vDEV - 92 (git e9150d72)
 - Slimefun Version: vDEV - 784 (git ac590fdd)
 - Plugin Version: vDEV - 6 (git 319b40ca)

**Comment by Seggan** [comment]
I am aware of this, unfortunately nothing can be done for a while as fixing it would break people on earlier Slimefun versions

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
> I am aware of this, unfortunately nothing can be done for a while as fixing it would break people on earlier Slimefun versions

Hello thanks for your patience.
Could u tell me where I will be able to find updates?

**Comment by Seggan** [comment]
https://thebusybiscuit.github.io/builds note that the fix is not out yet

**Comment by ProfElements** [comment]
> I am aware of this, unfortunately nothing can be done for a while as fixing it would break people on earlier Slimefun versions

Can we not just check the slimefun version and go from there?

**Comment by Seggan** [comment]
No. The old API doesn't exist in the newer versions
