### ISSUE TITLE
Hello new problem from slimefun

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [Seggan/Liquid#8]
Hello, I just sent a report to slimefun, but they just turned the problem to you... So why I'm here.

You can get all informations here https://github.com/Slimefun/Slimefun4/issues/2768

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I don't know if it is an error... but maybe yes...

**Comment by Seggan** [comment]
Duplicate of #6, will be fixed soon

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
thanks
